repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: name-tests-test
      #   args: [--django]
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          - pyproject-flake8
          - radon

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.931'
  #   hooks:
  #     - id: mypy
  #       args:
  #         - --ignore-missing-imports
  #       additional_dependencies:
  #         - strawberry-graphql
  - repo: local
    hooks:
      - id: mypy
        language: system
        name: check py typing
        entry: mypy .
        pass_filenames: false
        always_run: true
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: '21.12b0'
    hooks:
      - id: black
        args:
          - --check

  - repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args:
          - --check-only
        additional_dependencies:
          - toml

  - repo: local
    hooks:
      - id: test-schema
        language: system
        name: output test schema
        entry: sh -c "python -m strawberry export-schema tests.graphql_server:schema > tests/schema.graphql"
        pass_filenames: false
        always_run: true
        stages: [commit]

  - repo: local
    hooks:
      - id: test-dataclass-query
        language: system
        name: output dataclass query
        entry: python main.py -s ./tests/schema.graphql -q ./tests/queries/ -c ./tests/dataclass-conf.yml
        pass_filenames: false
        always_run: true
        stages: [commit]

  - repo: local
    hooks:
      - id: test-typeddict-query
        language: system
        name: output typeddict query
        entry: python main.py -s ./tests/schema.graphql -q ./tests/queries/ -c ./tests/typeddict-conf.yml
        pass_filenames: false
        always_run: true
        stages: [commit]
