# @generated AUTOGENERATED file. Do not Change!
# flake8: noqa
# fmt: off
# isort: skip_file

import typing
import copy
from dataclasses import dataclass
from gql import gql, Client


def rewrite_typename(value: typing.Any):
    if isinstance(value, dict) and '__typename' in value:
        value = copy.copy(value)
        value['_typename'] = value.pop('__typename')
    return value



@dataclass
class AllHumanSubsc__allHuman:
    id: str
    name: str


@dataclass
class AllHumanSubscResponse:
    allHuman: AllHumanSubsc__allHuman
    def __init__(self, allHuman):
        self.allHuman = AllHumanSubsc__allHuman(**rewrite_typename(allHuman))


_AllHumanSubscInput__required = typing.TypedDict("_AllHumanSubscInput__required", {})
_AllHumanSubscInput__not_required = typing.TypedDict("_AllHumanSubscInput__not_required", {}, total=False)


class _AllHumanSubscInput(_AllHumanSubscInput__required, _AllHumanSubscInput__not_required):
    pass


class AllHumanSubsc:
    Response: typing.TypeAlias = AllHumanSubscResponse
    Input: typing.TypeAlias = _AllHumanSubscInput
    _query = gql('''
        subscription AllHumanSubsc {
          allHuman {
            id name
          }
        }
    ''')
    @classmethod
    def subscribe(cls, client: Client, variable_values: _AllHumanSubscInput = {}) -> typing.Iterable[AllHumanSubscResponse]:
        for r in client.subscribe(cls._query, variable_values=variable_values):
            yield cls.Response(**rewrite_typename(r))  # type: ignore
    @classmethod
    async def subscribe_async(cls, client: Client, variable_values: _AllHumanSubscInput = {}) -> typing.AsyncIterable[AllHumanSubscResponse]:
        async for r in client.subscribe_async(cls._query, variable_values=variable_values):
            yield cls.Response(**rewrite_typename(r))  # type: ignore
